server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:testdb

jpa:
  show-sql: true
  hibernate:
    ddl-auto: create
  generate-ddl: true

h2:
  console:
    enabled: true
